### ISSUE TITLE
periodicPatternMDL v0

### ISSUE THREAD

**Issue by remiadon** [scikit-mine/scikit-mine#84]
#### Describe the workflow you want to enable
We would like to add a method for periodic patterns
["Mining periodic pattern with an MDL criterion" by Galbrun & Al.](https://arxiv.org/pdf/1807.01706.pdf)

Implementation is available [here](https://github.com/nurblageij/periodic-patterns-mdl)

#### Describe your proposed solution
The kind of workflow we want
```python
>>> from skmine.periodic import PeriodicPatternMDL
>>> from skmine.datasets import fetch_sacha_logs
>>> sacha_logs = fetch_sacha_logs(); sacha_logs
0
2018-04-16 07:30:00           wake up
2018-04-16 07:40:00    prepare coffee
2018-04-16 08:10:00        take metro
2018-04-16 11:00:00    attend meeting
2018-04-16 11:00:00        eat dinner
2018-04-17 07:32:00           wake up
2018-04-17 07:38:00    prepare coffee
2018-04-20 07:28:00           wake up
2018-04-20 07:41:00    prepare coffee
2018-06-15 07:28:00           wake up
Name: sacha, dtype: object
>>> sacha_logs.index.month  # accessing datetimes attributes with pandas
Int64Index([4, 4, 4, 4, 4, 4, 4, 4, 4, 6], dtype='int64', name=0)
>>> ppm = PeriodicPatternMDL()
>>> ppm.fit_discover(sacha_logs)  #only extract cycles for now
            event      length    period               start
0         wake up         5     24 hours     2018-04-16 07:30:00
1  prepare coffee         5     24 hours     2018-04-16 07:40:00
```

#### TODO
- [x] get hands on the existing code
- [ ] implement make_periodic method OR fetch_* methods to load datasets via skmine (eg. `fetch_sacha_logs`)
- [x] implement cycle extraction (first step toward a complete implementation)
- [x] unittests for cycle extraction
- [x] implement reconstruction method (reconstruct original dataset from cycles + residuals)
 - [x] add documentation

**Comment by remiadon** [comment]
@nurblageij I have a few questions concerning cycle extraction

I tried with the following small dataset
```csv
2018-04-16 7:30,wake up
2018-04-17 7:32,wake up
2018-04-18 7:30,wake up
2018-04-19 7:30,wake up
2018-04-20 7:30,wake up
2018-04-23 7:33,wake up
2018-04-24 7:32,wake up
2018-04-25 7:30,wake up
2018-04-26 7:30,wake up
2018-04-27 7:30,wake up
```

if I try to compute costs like explained in the paper 
<img width="493" alt="Screen Shot 2020-11-12 at 13 11 10" src="https://user-images.githubusercontent.com/2931080/98938731-a2f65f80-24e8-11eb-8859-4b60caeb9348.png">

We know the event : alpha = "wake up", in order to compute L(C) we have
```python
r = 10 (10 events for alpha)
tau = "2018-04-16 7:30" (datetime format)
inters = [1d+2m, 1d-2m, 1d, 1d, 3d+3m, 1d-1m, 1d-2m, 1d, 1d]  (differences between occurrences)
p = median(inters) --> 1day
E = [i - p for i in inters] --> [2m, -2m, 0, 0, 2d+3m, -1m, -2m, 0, 0]
delta_S = 11 days (same hour on monday first week to friday of next week) 
small_sigma_E = 2m - 2m + 2d+3m - 1m - 2m = 2 days
```

now applying the formulae
```python
L(p) = log2((11days - 2 days) / (10 - 1)) = log2(9 days / 1) = log2(1440 minutes)
L(tau) = log2(11days - 2 days - (10 - 1) * 1day + 1) = log2(11days - 2 days - 9days + 1) = log2(1) = 0
L(C) = log2(|S|) + L(p) + L(tau) + 2|E| + sum([|e| for e in E])
L(C) = log2(10) + log2(1440 minutes) + 0 + 2*9 + 2days10minutes
L(C) = 3.32 + 10.49 + 0 + 18 + 2890
```

A few problems here
1) I am adding minute and pure numbers, as I turn every time-related into minutes. Does that seem normal ? I could do the same turning everything into seconds ?
2) The final L(C) is big, mainly because of the last term, which is equal to 2890 minutes. From what I understand in this term we sum absolute values from E. As I have a weekend inbetween the two weeks of logs, most of this cost if coming from this weekend, which represents a big inter-occurence delay. Do I need to sub-divide those two weeks before ?

Thanks, Rémi

**Comment by nurblageij** [comment]
1) All times should be turned into unit-less numerical values at a chosen resolution (second, minutes, hours, five minutes, etc.) depending on the application considered.
Can also consider data where the order of events matters, without absolute timing.
2) The parts from the two weeks with a gap in between would likely not be considered as a single cycle but as two cycles (which might later be combined into more complex pattern, especially if it repeats similarly in following weeks)
That's precisely because the cost of the inter-occurrence gap caused by the week-end is large and makes the long cycle more costly than the two separate cycles.
It's one improvement we have thought about but not implemented, to add a way to encode "jumps over absent occurrences" which would allow to bridge gaps more cheaply (which would be useful, as long as the gaps in turn are not periodic...).
I hope that helps...

**Comment by remiadon** [comment]
Thank you for you answers

Now I think we can extract a pseudo-code for cycle extraction
```python

def extract_cycles(S):
   """ S is a list of occurences. An occurence is a timestamp–event pair like (2, c)"""
   alphas = unique events from S
   tot_cost = sum(L(o)=L(t) + L(alpha) for o in S)
   for alpha in alphas:
       S_alpha = subset of S corresponding to alpha
       r = len(S_alpha) - 1
       tau = S_alpha[0][0]  # first index in pair for first element --> timestamp for first event
       inters = [S_alpha[i][0] - S_alpha[i - 1][0] for i in range(len(S_alpha))]
       p = median(inters)
       L(C) = compute cost of cycle given alpha, r, tau, p
       residuals_cost = sum(L(o)=L(t) + L(alpha) for o in S if o not covered by C)
       if L(C) + residuals_cost < tot_cost:
              output C = alpha, r, tau, p
```

@nurblageij do you agree ? 🔢

**Comment by nurblageij** [comment]
I think that's not quite it.
In the pseudo code above, it's going over each event in the alphabet and computing the cost of covering all occurrences of that event with a single cycle.
But it needs to find the small cycles, covering a subset of occurrences of the event that are cost-efficient, not just consider a single one covering everything, which typically is no good. 
In _extract_cycles_alpha_,
first it tries with a dynamic programming strategy, this is what happens in _compute_cycles_dyn_
then tries with a heuristic based on triples on the left over, in _extract_cycles_fold_
the cycles obtained with both strategies are then merged and filtered.

**Comment by nurblageij** [comment]
Something that might be confusing:
there is a function _compute_cycles_fold_ which applies only the triples heuristic in _extract_cycles_fold_
which is no longer used, I think, and replaced by the combination of both dynamic programming and triples heuristic in  _extract_cycles_alpha_

**Comment by remiadon** [comment]
@nurblageij yes I over simplified it. What's missing is finding the "small cycles" as you said

>  then tries with a heuristic based on triples on the left over
What do you mean by "triples on the left over" ?

My first thought for the "small cycles" would be 
1. start with all events corresponding to alpha, namely S_alpha
2. compute p, being the median of all shifts
3. find cuts points by filtering events being greater than p by a factor (eg. all shifts bigger than p by 1.5 --> we find the weekend between two weeks)
4. recurse on all subsets of S_alpha divided by the cut points

Would this make sense ?

**Comment by nurblageij** [comment]
Well, finding the small cycles is all it is about...
By " tries with a heuristic based on triples on the left over" I meant it first finds some cycles with the dynamic programming, then tries the triples heuristic on the occurrences that are not covered by those cycles, i.e. left-over occurrences.
The top-down approach you suggest is yet another heuristic, I can't tell for sure how it would perform. But it's not just a matter of breaking the long cycle into smaller pieces, there might be cycles overlapping/interleaving, which I doubt you'd find with this kind of approach.
I think it's best to follow the original algorithm based on the two heuristics as implemented and as explained in the publication.

**Comment by remiadon** [comment]
@nurblageij sorry I just found out there were explanations for ExtractCyclesDP and ExtractCyclesTri in the long version of the paper

**Comment by nurblageij** [comment]
no problem. The explanations in the paper don't go deep into technical details, and there is no one-to-one mapping of functions, but hopefully it helps get the overall idea how things proceed, and why.

**Comment by remiadon** [comment]
@nurblageij there is still something I don't understand in your implementation.

At the very beginning you compute a dictionary of metadata for the input data, named 'data_details'
In this dictionary there is a value called `blck_delim`, which is usually set to a non-null float value.
Later on this value is used as alpha when compute the cycle length. I just don't understand how you compute this value, and what it represents.

Part of your code I am mentioning is [here](https://bitbucket.org/galbrun/per-pat/src/dc4683e6b51007f97ca5893fe861b53a696cbcaf/PeriodicPatternsMDL_RR/scripts/classPatterns.py#lines-117)

**Comment by nurblageij** [comment]
blck_delim stands for block delimiter
The variable stores the number of bits needed to encode symbols for delimiting blocks when specifying the events (this is most relevant for complex patterns), the parenthesis at the beginning and end. see "Encoding the patterns" on page 14 of the long report.
If only simple patterns are considered, the separators could be skipped, there won't be anything to separate...
