### ISSUE TITLE
PeriodicPatternMiner

### ISSUE THREAD

**Issue by remiadon** [scikit-mine/scikit-mine#87]
#### Describe the workflow you want to enable
This issue has introduced a PeriodicCycleMiner class, that aims at discovering simple cycles in log data

Now we want to extract richer periodic patterns, in the form of trees

#### TODO
- [x] get hands on the existing code
- [ ] implement PeriodicPatternMiner, based on PeriodicCycleMiner
- [ ] unittests for cycle extraction
- [ ] implement reconstruction method ?
- [ ] add documentation

**Comment by remiadon** [comment]
@nurblageij
Now I have questions concerning the tree patterns
<img width="515" alt="Screen Shot 2020-12-09 at 13 58 49" src="https://user-images.githubusercontent.com/2931080/101633054-05c71200-3a27-11eb-90b8-92c6e004808b.png">



Let's start with the `CombineVertically` heuristic. 
<img width="535" alt="Screen Shot 2020-12-09 at 14 00 11" src="https://user-images.githubusercontent.com/2931080/101632950-dfa17200-3a26-11eb-8f22-875dd6b0f9a0.png">

1) I don't understand where the `P` parameter comes from when calling CombineVertically in algorithm 2. I guess it's instantiated to an empty set of trees, and returned at the very end of the algorithm
2) If I understand well we start with simple cycles at the very beginning (H is instantiated to the basic cycles found in the data), and we look for triples via the ExtractCyclesTri method. I dont understand how we shoud compute the l_max for this function (line 4 in algorithm 4.)
