### ISSUE TITLE
fetch_* methods for logs

### ISSUE THREAD

**Issue by remiadon** [scikit-mine/scikit-mine#88]
#### Describe the workflow you want to enable
Especially for periodic pattern mining we need logging data

A `fetch_health_app` has already been introduced in https://github.com/scikit-mine/scikit-mine/pull/86

We want to be able to fetch other log datasets easily

#### TODO
- [ ] fetch methods for [Log Hub](https://github.com/logpai/loghub), where all .csv file contain only 2k entries
- [x] fetch methods for [Canadian TV](https://open.canada.ca/data/en/dataset/800106c1-0b08-401e-8be2-ac45d62e662e#wb-auto-6)
- [x] documentation 
- [x] unit tests 
- [ ] user test by Laurent Guillo

Documentation should be integrated in https://scikit-mine.github.io/scikit-mine/reference/datasets.html

The data for Canadian TV is here https://applications.crtc.gc.ca/OpenData/Television%20Logs/STAR2/2020/2020-08.zip
filename : CBC_202008_*.log

Notes for data loading:
 - filter out commercials, only keep the base event (TV series episodes)
 - the timestamp should be in

**Comment by remiadon** [comment]
Question for Laurent
 - Is the doc clear enough ?
 - What about the structure ? Having a hierarchy by module as in https://github.com/scikit-mine/scikit-mine/pull/94 is to consider ?
